---
title: "Top 3 Keywords per SKU"
date: "03 December 2015"
output: rmarkdown::tufte_handout
---

# Most Clickable Key words per SKU 

```{r read_in_data, cache = T, echo = F}
dataFile = "/Users/loganscalder/Google Drive/EliteTechGear/Data/To Be Categorized/campaign-performance-report-2015-10-03-60124016771.txt"

x = read.delim(file = dataFile, 
               nrows = 1000) # read in part of the data to get the colClasses
classes = sapply(x, class)  # use the column classes to speed up the read in
x = read.delim(file = dataFile, # read in all the data
               colClasses = classes)
```

```{r,  echo = F, message = F}
require(plyr)
require(knitr)
```


```{r key_words_generate, echo = F, cache = T}


keyWords = 
    ddply(x, 
          .var = .(Advertised.SKU, Keyword),
          .fun = summarise,
          Clicks = sum(Clicks),
          Impressions = sum(Impressions),
          CTR = round(Clicks/Impressions, 3)
          )

topKeyWords = 
    ddply(keyWords,
          .var = "Advertised.SKU",
          .fun = function(x){
              ordered = arrange(x,CTR,decreasing = T)  # arrange by CTR
              top = na.omit(ordered[1:3,])  # choose top 3, remove NA's
              # NA's come from choosing 1:3 when there is less than 3 to choose
          })


kable(topKeyWords)
write.csv(x = topKeyWords, file = "Reports/topKeyWords.csv")
```





