---
title: "Daily Shiny Report"
author: "Logan Calder"
date: "February 11, 2016"
output: html_document
runtime: shiny
---

```{r packages}
require(ggvis)
require(reshape)
require(plyr)
require(dplyr)
require(shiny)
```

```{r directories}
projDir = getwd()
```

```{r sku_data_dir}
sku_data_dir = "/Users/loganscalder/Google Drive/EliteTechGear/Data/SKU Performance"
```



```{r read_in_bsr}
setwd(sku_data_dir)
bsr = read.csv("DailySKUBSR.csv")
weeklySkuPerformance = read.csv("WeeklySKUSalesUnitsOrders.csv")

bsr  = 
    bsr %>% 
        mutate(
            Date = as.Date(as.character(Date), 
                           format = "%d/%m/%y")
            )
```

```{r bsr_data_quality_control}
# Are there dates with far fewer entries?
t = table(bsr$Date)

# Dates with more than one entry per product?
t = table(bsr[c("Date", "SKU")])
# Are there outlier sku's?
t = table(bsr["SKU"])
# Are there rankings that look out of place? I don't think I can answer that.
```


```{r shiny_app}
shinyAppDir()
```

